server:
  port: 8080
#-----------------------------------ES数据库配置----------------------------------------
elasticsearch:
  rest:
    username: elastic
    password: 654321
    url: 106.13.229.155:9200

elasticUserPassword: elastic:654321
elasticIp: 106.13.229.155
#------------------------------------redis配置、Mysql配置---------------------------------------
spring:
  servlet:
    multipart:
      max-file-size: 1000GB
      max-request-size: 9000GB
  datasource:
    url : jdbc:mysql://127.0.0.1:3306/jee?useUnicode=true&characterEncoding=UTF-8
    username : root
    password : root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

#     url: jdbc:sqlite::resource:db/test.db
#     driver-class-name: org.sqlite.JDBC
#     username:
#     password:
#redis配置
redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  timeout: 10000
  pool:
    # 最大可用连接数（默认为8，负数表示无限）
    max-active: 200
    # 最大空闲连接数（默认为8，负数表示无限）
    max-idle: 8
    # 最小空闲连接数（默认为0，该值只有为正数才有作用）
    min-idle: 0
    # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
    max-wait: -1


#集成mybatis
mybatis:
  mapper-locations: classpath:xml/*.xml
  type-aliases-package: com.ghkj.gaqentity
  configuration:
    # 开启驼峰映射
    map-underscore-to-camel-case: true

# pageHelper分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

#控制台打印sql
logging:
  level:
    com.ghkj.gaqdao.mapper: debug

matchAllNum: 10000
uploadImages: /home/images/
upload:
  #localtion: ${UPLOAD_DIR:/home/data/test}
  localtion: D://test//
  maxFileSize: 100MB
  maxRequestSize: 1000MB

# AES密码加密私钥(Base64加密)
encryptAESKey: V2FuZzkyNjQ1NGRTQkFQSUpXVA==
# JWT认证加密私钥(Base64加密)
encryptJWTKey: U0JBUElKV1RkV2FuZzkyNjQ1NA==
# AccessToken过期时间-5分钟-5*60(秒为单位)
accessTokenExpireTime: 300
# RefreshToken过期时间-30分钟-30*60(秒为单位)
refreshTime: 1800
# Shiro缓存过期时间-5分钟-5*60(秒为单位)(一般设置与AccessToken过期时间一致)
shiroCacheExpireTime: 300















