server:
  port: 8080
#-----------------------------------ES数据库配置----------------------------------------
elasticIp: 192.168.1.17
elasticUserPassword: elastic:123456
#------------------------------------redis配置、Mysql配置---------------------------------------
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  datasource:
    url : jdbc:mysql://127.0.0.1:3306/jee?useUnicode=true&characterEncoding=UTF-8
    username : root
    password : root
    driverClassName : com.mysql.jdbc.Driver
  cache:
    type: redis
  redis:
      host: 192.168.1.17
      port: 6379
      password: 123456
      timeout: 20000
      pool:
      # 最大可用连接数（默认为8，负数表示无限）
      max-active: 8
      # 最大空闲连接数（默认为8，负数表示无限）
      max-idle: 8
      # 最小空闲连接数（默认为0，该值只有为正数才有作用）
      min-idle: 0
      # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
      max-wait: -1

#集成mybatis
mybatis:
  mapper-locations: classpath:xml/*.xml
  type-aliases-package: com.ghkj.gaqentity

mapper:
  mappers: com.ghkj.gaqcommons.untils.MyMapper
  not-empty: false
  identity: MYSQL

# pageHelper分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


#控制台打印sql
logging:
  level:
    com.ghkj.gaqdao.mapper: debug

matchAllNum: 10000
uploadImages: /home/images/











